-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 19:30:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TCC_2022
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `EnderecoPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnderecoPessoa` (
  `IDEnderecoPesssoa` INT NOT NULL,
  `Numero` INT NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`IDEnderecoPesssoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pessoa` (
  `IDPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `CPF` CHAR(14) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL,
  `DataInsercao` DATE NULL,
  `Telefone` VARCHAR(45) NULL,
  `CaminhoImagem` VARCHAR(45) NULL,
  `Verificado` TINYINT NULL,
  `NivelAcesso` VARCHAR(45) NULL,
  `IdEnderecoPesssoa` INT NOT NULL,
  PRIMARY KEY (`IDPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnderecoImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnderecoImovel` (
  `IDEnderecoImovel` INT NOT NULL,
  `Numero` INT NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`IDEnderecoImovel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imovel` (
  `IDImovel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Capacidade` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Descrição` TEXT NULL,
  `Valor` DOUBLE NULL,
  `CaminhoImagem` VARCHAR(45) NULL,
  `IDEnderecoImovel` INT NOT NULL,
  `IDPessoa` INT NOT NULL,
  PRIMARY KEY (`IDImovel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pagamento` (
  `IDPagamento` INT NOT NULL,
  `Metodo` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `PaymentID` VARCHAR(45) NULL,
  `SellerID` VARCHAR(45) NULL,
  `Amount` DOUBLE NULL,
  `OrderID` VARCHAR(45) NULL,
  `Received` VARCHAR(45) NULL,
  `TransactionID` VARCHAR(45) NULL,
  `JsonRecebido` VARCHAR(45) NULL,
  `IPUser` VARCHAR(45) NULL,
  `Session` VARCHAR(45) NULL,
  `DataModificacao` DATE NULL,
  `CustomerID` VARCHAR(45) NULL,
  PRIMARY KEY (`IDPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comodo` (
  `IDComodo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`IDComodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agenda` (
  `IDAgenda` INT NOT NULL,
  `DataEntrada` DATETIME NULL,
  `DataSaida` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `IDPessoa` INT NOT NULL,
  `IDPagamento` INT NOT NULL,
  `Comentario` TEXT NULL,
  `Nota` INT NULL,
  `IDImovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDAgenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mobilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mobilia` (
  `IDMobilia` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Capacidade` INT NULL,
  PRIMARY KEY (`IDMobilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComodoMobilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComodoMobilia` (
  `IDComodoMobilia` INT NOT NULL,
  `IDComodos` INT NOT NULL,
  `IDMobilia` INT NOT NULL,
  PRIMARY KEY (`IDComodoMobilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComodoImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComodoImovel` (
  `IDComodoImovel` VARCHAR(45) NOT NULL,
  `IDComodo` INT NOT NULL,
  `IDImovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDComodoImovel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Feedback` (
  `IDFeedback` INT NOT NULL,
  `Comentario` TEXT NULL,
  `Data` DATE NULL,
  `Nota` INT NULL,
  `IDPessoa` INT NOT NULL,
  PRIMARY KEY (`IDFeedback`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
